# Generated by Django 3.2.4 on 2021-09-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='itemsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='productmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('pdesc', models.CharField(max_length=50)),
                ('pprice', models.FloatField()),
                ('pdiscount', models.FloatField()),
                ('ppic', models.ImageField(upload_to='')),
                ('itemid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online.itemsmodel')),
            ],
        ),
    ]
